<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQboxKCE\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQboxKCE/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerQboxKCE.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerQboxKCE\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerQboxKCE\App_KernelDevDebugContainer([
    'container.build_hash' => 'QboxKCE',
    'container.build_id' => '950ebd16',
    'container.build_time' => 1712156072,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQboxKCE');
