<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerF4xgOag\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerF4xgOag/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerF4xgOag.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerF4xgOag\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerF4xgOag\App_KernelDevDebugContainer([
    'container.build_hash' => 'F4xgOag',
    'container.build_id' => 'd84ca8a9',
    'container.build_time' => 1713261832,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerF4xgOag');
