<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKfy6CtL\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKfy6CtL/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerKfy6CtL.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerKfy6CtL\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerKfy6CtL\App_KernelDevDebugContainer([
    'container.build_hash' => 'Kfy6CtL',
    'container.build_id' => 'a7bf6082',
    'container.build_time' => 1712239544,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKfy6CtL');
